# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cta/Documents/Projects/SnakePong

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cta/Documents/Projects/SnakePong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cta/Documents/Projects/SnakePong/CMakeFiles /home/cta/Documents/Projects/SnakePong/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cta/Documents/Projects/SnakePong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named snake

# Build rule for target.
snake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snake
.PHONY : snake

# fast build rule for target.
snake/fast:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/build
.PHONY : snake/fast

GameLogic/GameState.o: GameLogic/GameState.cpp.o

.PHONY : GameLogic/GameState.o

# target to build an object file
GameLogic/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/GameState.cpp.o
.PHONY : GameLogic/GameState.cpp.o

GameLogic/GameState.i: GameLogic/GameState.cpp.i

.PHONY : GameLogic/GameState.i

# target to preprocess a source file
GameLogic/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/GameState.cpp.i
.PHONY : GameLogic/GameState.cpp.i

GameLogic/GameState.s: GameLogic/GameState.cpp.s

.PHONY : GameLogic/GameState.s

# target to generate assembly for a file
GameLogic/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/GameState.cpp.s
.PHONY : GameLogic/GameState.cpp.s

GameLogic/MenuState.o: GameLogic/MenuState.cpp.o

.PHONY : GameLogic/MenuState.o

# target to build an object file
GameLogic/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/MenuState.cpp.o
.PHONY : GameLogic/MenuState.cpp.o

GameLogic/MenuState.i: GameLogic/MenuState.cpp.i

.PHONY : GameLogic/MenuState.i

# target to preprocess a source file
GameLogic/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/MenuState.cpp.i
.PHONY : GameLogic/MenuState.cpp.i

GameLogic/MenuState.s: GameLogic/MenuState.cpp.s

.PHONY : GameLogic/MenuState.s

# target to generate assembly for a file
GameLogic/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/MenuState.cpp.s
.PHONY : GameLogic/MenuState.cpp.s

GameLogic/PlayerMove.o: GameLogic/PlayerMove.cpp.o

.PHONY : GameLogic/PlayerMove.o

# target to build an object file
GameLogic/PlayerMove.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/PlayerMove.cpp.o
.PHONY : GameLogic/PlayerMove.cpp.o

GameLogic/PlayerMove.i: GameLogic/PlayerMove.cpp.i

.PHONY : GameLogic/PlayerMove.i

# target to preprocess a source file
GameLogic/PlayerMove.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/PlayerMove.cpp.i
.PHONY : GameLogic/PlayerMove.cpp.i

GameLogic/PlayerMove.s: GameLogic/PlayerMove.cpp.s

.PHONY : GameLogic/PlayerMove.s

# target to generate assembly for a file
GameLogic/PlayerMove.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/PlayerMove.cpp.s
.PHONY : GameLogic/PlayerMove.cpp.s

GameLogic/StateManager.o: GameLogic/StateManager.cpp.o

.PHONY : GameLogic/StateManager.o

# target to build an object file
GameLogic/StateManager.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/StateManager.cpp.o
.PHONY : GameLogic/StateManager.cpp.o

GameLogic/StateManager.i: GameLogic/StateManager.cpp.i

.PHONY : GameLogic/StateManager.i

# target to preprocess a source file
GameLogic/StateManager.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/StateManager.cpp.i
.PHONY : GameLogic/StateManager.cpp.i

GameLogic/StateManager.s: GameLogic/StateManager.cpp.s

.PHONY : GameLogic/StateManager.s

# target to generate assembly for a file
GameLogic/StateManager.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameLogic/StateManager.cpp.s
.PHONY : GameLogic/StateManager.cpp.s

GameObjects/Snake.o: GameObjects/Snake.cpp.o

.PHONY : GameObjects/Snake.o

# target to build an object file
GameObjects/Snake.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameObjects/Snake.cpp.o
.PHONY : GameObjects/Snake.cpp.o

GameObjects/Snake.i: GameObjects/Snake.cpp.i

.PHONY : GameObjects/Snake.i

# target to preprocess a source file
GameObjects/Snake.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameObjects/Snake.cpp.i
.PHONY : GameObjects/Snake.cpp.i

GameObjects/Snake.s: GameObjects/Snake.cpp.s

.PHONY : GameObjects/Snake.s

# target to generate assembly for a file
GameObjects/Snake.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/GameObjects/Snake.cpp.s
.PHONY : GameObjects/Snake.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... snake"
	@echo "... GameLogic/GameState.o"
	@echo "... GameLogic/GameState.i"
	@echo "... GameLogic/GameState.s"
	@echo "... GameLogic/MenuState.o"
	@echo "... GameLogic/MenuState.i"
	@echo "... GameLogic/MenuState.s"
	@echo "... GameLogic/PlayerMove.o"
	@echo "... GameLogic/PlayerMove.i"
	@echo "... GameLogic/PlayerMove.s"
	@echo "... GameLogic/StateManager.o"
	@echo "... GameLogic/StateManager.i"
	@echo "... GameLogic/StateManager.s"
	@echo "... GameObjects/Snake.o"
	@echo "... GameObjects/Snake.i"
	@echo "... GameObjects/Snake.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

